name: .NET Core

on:
  workflow_dispatch:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/DataMasker/DataMasker.csproj
    - name: Build
      run: dotnet build ./src/DataMasker/DataMasker.csproj --configuration Release --no-restore
    - name: Publish      
      run: dotnet publish ./src/DataMasker/DataMasker.csproj --configuration Release --no-restore -o ./build/
    - name: Collect Artifact 
    - uses: actions/upload-artifact@v2
      with:
        name: build.${{GITHUB_RUN_NUMBER}}
        path: ./build/**.*
    
