name: .NET Core

on:
  workflow_dispatch:
  
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/DataMasker/DataMasker.csproj
    - name: Build
      run: dotnet build ./src/DataMasker/DataMasker.csproj --configuration Release --no-restore 

